add_new_device_button = "id:addButton"
all_devices_device_status = "css:.device-container .device-status span:first-child"
nextBtn = "id:next"
backBtn = "id:Create"
scanSettingBtn = "id:scan-settings"
fromAddress = "css:.settings-div-ip-range input:first-child"
toAddress = "css:.settings-div-ip-range input:last-child"
portSetting ="css:.settings-div .textInput.port"
startScanBtn = "class:Start scan"
deviceHeaderCheckBox = "id:deviceHeaderCheckbox"
addDeviceBtn = "id:addDevice"
writePasswordField = "xpath:(//input[@id='password'])[1]"
readPasswordField = "xpath:(//input[@id='password'])[2]"
writeConfirmPasswordField = "xpath:(//input[@id='confirmPassword'])[1]"
readConfirmPasswordField = "xpath:(//input[@id='confirmPassword'])[2]"
writeShowPassword = "xpath:(//input[@id='showPassword'])[1]"
readShowPassword =  "xpath:(//input[@id='showPassword'])[2]"
protectProjectBtn = "id:setuppassword"
deviceUserName = "id:username"
devicePassword = "id:password"
skipBtn ="css:.btn.ski"
loginBtn = "id:login"
exposed_server_inf = "css:.init-dummy"

# Add new device page locators
add_new_device_dialog_header = "css:app-form-dialog .header-text"
add_new_device_dialog_next_button = "css:app-form-dialog button#next"
add_new_device_dialog_device_selector = "css:app-form-dialog app-device-browse-selector"
add_new_device_dialog_scan_settings = "css:app-form-dialog #scan-settings"
add_new_device_dialog_start_scan = "css:app-form-dialog .button-scan"
add_new_device_dialog_select_all_devices= "css:app-form-dialog #deviceHeaderCheckbox"
add_new_device_dialog_add_devices_button= "css:app-form-dialog button#addDevice"
add_new_device_dialog_scan_settings_ip_from_input = "css:app-form-dialog .settings-div-ip-range input:first-child"
add_new_device_dialog_scan_settings_ip_to_input = "css:app-form-dialog .settings-div-ip-range input:last-child"
add_new_device_dialog_selected_device_mechanism = "css:device-add-mechanism-selector label:has(input:checked)"
add_new_device_dialog_found_devices = "css:app-devices-scan tr.device-grid-body"
add_new_device_Manual_Entry_Text_Field_id = "css:app-form-dialog #address"
add_new_device_Manual_Entry_Tab_id = "css:app-form-dialog .p-tabview-nav li:nth-child(2)"
btn_addNewDeviceManualConnect = "css:app-form-dialog .button-next"
add_new_device_password_field= "css:app-form-dialog #password"
add_new_device_confirm_password_field= "css:app-form-dialog #confirmPassword"
btn_protect_project_setuppassword='css:app-form-dialog #setuppassword'
btn_read_file = "css:.import-from-file .button-next"
import_device_radio_btn = "xpath:(//*[@type='radio'])[2]"
cancel_scan_button='css:.footer-toolbar .btn-cancel-label'
cancel_scan_grid_text = "css:app-devices-scan .scan-container table tr:nth-child(1) td:nth-child(1)"

# Delete device  locators
delete_device_header = "css:.device-container .device-card-header"
delete_device_Ok_btn = "id:deleteIcon"
ok_button_delete_device_popup = "id:ok"
device_address_column = "xpath:(//*[starts-with(@class,'device-grid-body')])[${Row_no}]/td[3]/*"
device_name_column = "xpath:(//*[starts-with(@class,'device-grid-body')])[${Row_no}]/td[2]/*"
green_check = "css:.fa.fa-check-circle"
btn_import_cancel = "xpath:(//*[contains(text(),'Cancel')])[2]"
select_device = "css:#selectDevice"
all_devices_titles = "xpath:(//*[contains(@class,'deviceName')])[${element_no}]"
all_devices_IP = "xpath://*[@title = 'Edit IP address']"
btn_update_device = "css:span.device-card-header-sync .fas.fa-sync"
device_card_body = "css:.device-card-body"
Device_credentail_POPUP = "xpath://*[@class='header-text' and contains(text(),'Browse Device')]" 
project_protection_POPUP = "xpath://*[@class='header-text' and contains(text(),'Password protection for the project is required.')]"
#all_devices_titles = "xpath:(//*[@class='device-card-header--title'])[${element_no}]"
device_card_container= "css:.device-container"
