confirm_window_description = "css:app-overlay .dialog-content-message-description"
confirm_window_header = "css:app-overlay .header-text"
confirm_window_ok_button = "css:app-overlay button#ok"
confirm_window_no_button = "css:app-overlay button#optional"
confirm_window_confirm_icon = "css:app-overlay .confirm-icon"
confirm_window_success_icon = "css:app-overlay .success-icon"
confirm_add_device_button = "xpath://*[contains(@class,'footer-toolbar')]//*[contains(text(),'OK')]"
confirm_add_device_Cancel_button = "//*[contains(@class,'footer-toolbar')]//*[contains(text(),'Cancel')]"

side_menu_device_tree_icon = "css:app-menu .p-menu-list li:nth-child(2) .p-menuitem-link"
side_menu_home_icon = "css:app-menu .p-menu-list li:first-child .p-menuitem-link"
side_menu_plant_view_icon = "css:app-menu .p-menuitem-icon.plantviewicon"
side_menu_settings_icon = "css:app-menu .settingsicon"

spinner = "css:div#overlay #spinner"
homeIcon = "css:.p-menuitem-icon.homeicon"
deviceIcon = "css:.p-menuitem-icon.devicetreeicon"
editorIcon = "css:.p-menuitem-icon.plantviewicon"
settingsIcon = ".p-menuitem-icon.settingsicon"
DialogueBox = "css:.p-card.p-component"
confirm_window_description = "css:app-overlay .dialog-content-message-description"
DialogueBoxHeader = "css:.header.p-toolbar.p-component"
btn_yes = "id:ok"
btn_no = "css:#optional"
projectSelect = "xpath://*[contains(@class,'p-element p-datatable-tbody')]//*[contains(@title,'${name}')]"
projectSelected = "xpath://*[contains(@class,'p-element p-datatable-tbody')]" \
                  "//*[contains(@class,'project-selected')]//*[contains(@title,'${name}')]"
errorpop = "css:.err-span"
confirm_window_success_icon = "css:app-overlay .success-icon"
confirm_window_error_icon = "css:app-overlay .error-icon"
close_dialog = "css:.close-dialog"
delete_icon = "css:.action-bar"
close_error_popup = "css:app-overlay #ok"

menu = "css:li .p-menuitem-link"
