button_create_project= "id:CreateButton"
button_delete_project = "css:.delete-project.project-enable"
no_opened_project_panel = "css:.p-accordion-tab .no-project-opened"
button_opened_project_3dot = "xpath://*[contains(@class,'dot')]"
opened_project_container = "css:.open-project__container"
opened_project_header = "css:.card__header--title"
opened_project_overlay_menu = "css:.p-menu-list"
opened_project_close_project_menuitem = "xpath://*[text()='Close project']"
opened_project_save_as_project_menuitem = "xpath://*[text()='Save as']"
opened_project_export_project_menuitem = "xpath://*[text()='Export project']"
button_opened_project_save_project = "css:.opened-project .save__project"

project_list_table = "css:.recently-used-project table"
project_in_project_list = project_list_table + " tr:has(td[title='${project_name}']:nth-child(2))"
project_in_project_list_selected = project_in_project_list + ".project-selected"
opened_project_in_project_list = project_in_project_list + " .opened"
project_last_changed_date = project_in_project_list + "#lastChanged"

save_as_popup = "xpath://*[contains(@class,'header-toolbar')]//*[contains(text(),'Save project as')]"
password_validation_modal_title = \
    "xpath://*[contains(@class,'header-toolbar')]//*[contains(text(),'${title}')]"

## This file contains the web elements of home page
btn_createNewProject = "id:CreateButton"
btn_import = "id:Importbutton"
Name = "id:name"
Comment = "id:comment"
Author = "input#author"
btn_create = "id:save"
btn_cancel = "id:cancel"
projectList = "css:.p-datatable-tbody"
SelectedProject =  "css:.project-selected.ng-star-inserted"
moreOption = "id:dotButton"
btn_exportProject = "css:.p-menuitem-icon.export-icon"
btn_closeProject = "css:.open-project-context li:nth-child(2)"
btn_saveAs = "css:.p-menuitem-icon.saveas-icon"
btn_edit = "id:editButton"
btn_openProject = "id:OpenButton"
btn_deleteProject = "id:DeleteButton"
projectCard = "css:.card.p-card"
browseBtn = "class:browse-btn"
bBtn = "xpath://*[contains(@class,'browse-btn')]"
fileSelect = "css:.file-browse-container"
btn_no = "id:optional"
btn_ok = "id:ok"
uploadBtn = "css:.browse-btn"
password_for_open_project = "css:app-form-dialog input#passwordText"
btn_open_or_delete_ProtectedProject = "id:setuppassword"
password_verification_popup = "css:#passwordValidationModal .header-text"
# create project dialog locators
create_project_dialog_author_field = "css:app-form-dialog input#author"
create_project_dialog_comment_field = "css:app-form-dialog textarea#comment"
create_project_dialog_header = "css:app-form-dialog .header-text"
create_project_dialog_name_field = "css:app-form-dialog input#name"
create_project_dialog_create_button = "css:app-form-dialog button#save"
project_lastmodified_date_time="css:.recently-used-project table  tr:has(td[title='${project_name}']) td:nth-child(6)"


